import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1773686919350 implements MigrationInterface {
    name = 'InitSchema1773686919350'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "slug" character varying(128) NOT NULL, "industry_type" character varying(128), "signup_source" character varying(32) NOT NULL DEFAULT 'self_service', "onboarded_by" uuid, "default_currency" character varying(16) NOT NULL DEFAULT 'BDT', "default_timezone" character varying(64) NOT NULL DEFAULT 'Asia/Dhaka', "receipt_footer" text NOT NULL DEFAULT 'Thank you!', "status" character varying(32) NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "tenants_slug_unique" UNIQUE ("slug"), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "branches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "code" character varying(64) NOT NULL, "address" text, "phone" character varying(32), "status" character varying(32) NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "branches_tenant_code_unique" UNIQUE ("tenant_id", "code"), CONSTRAINT "PK_7f37d3b42defea97f1df0d19535" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "branches_tenant_id_index" ON "branches" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "parent_id" uuid, "name" character varying(255) NOT NULL, "status" character varying(32) NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "categories_tenant_id_index" ON "categories" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "tax_groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "status" character varying(32) NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "tax_groups_tenant_name_unique" UNIQUE ("tenant_id", "name"), CONSTRAINT "PK_eae1ea5fef32cb6f21f4ab68d04" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "tax_groups_tenant_id_index" ON "tax_groups" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "category_id" uuid, "tax_group_id" uuid, "name" character varying(255) NOT NULL, "sku" character varying(64), "barcode" character varying(128), "unit" character varying(16) NOT NULL DEFAULT 'pcs', "price" numeric(12,2) NOT NULL, "cost" numeric(12,2) NOT NULL, "status" character varying(32) NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "products_tenant_barcode_unique" UNIQUE ("tenant_id", "barcode"), CONSTRAINT "products_tenant_sku_unique" UNIQUE ("tenant_id", "sku"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "products_tenant_id_index" ON "products" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "slug" character varying(50) NOT NULL, "is_system" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "roles_tenant_slug_unique" UNIQUE ("tenant_id", "slug"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "default_branch_id" uuid NOT NULL, "role_id" uuid NOT NULL, "full_name" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "phone" character varying(32), "password_hash" character varying(255) NOT NULL, "status" character varying(32) NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "users_tenant_id_index" ON "users" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "tax_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "tax_group_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "rate" numeric(5,2) NOT NULL, "is_inclusive" boolean NOT NULL DEFAULT false, "sort_order" integer NOT NULL DEFAULT '0', "status" character varying(32) NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fefada95a3b9edeac02a5c7b5dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "tax_configs_tenant_branch_group_index" ON "tax_configs" ("tenant_id", "branch_id", "tax_group_id") `);
        await queryRunner.query(`CREATE INDEX "tax_configs_tenant_branch_index" ON "tax_configs" ("tenant_id", "branch_id") `);
        await queryRunner.query(`CREATE TABLE "discount_presets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "type" character varying(16) NOT NULL, "value" numeric(12,2) NOT NULL, "scope" character varying(16) NOT NULL, "max_discount_amount" numeric(12,2), "min_order_amount" numeric(12,2), "valid_from" TIMESTAMP WITH TIME ZONE, "valid_until" TIMESTAMP WITH TIME ZONE, "is_combinable" boolean NOT NULL DEFAULT true, "status" character varying(32) NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4f211be816951bfed842b5d5aeb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "discount_presets_tenant_id_index" ON "discount_presets" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "discount_preset_branches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "discount_preset_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "discount_preset_branches_preset_branch_unique" UNIQUE ("discount_preset_id", "branch_id"), CONSTRAINT "PK_9ad41dee52611fd87bc566c61f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventory_batches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "type" character varying(32) NOT NULL, "description" text, "status" character varying(32) NOT NULL DEFAULT 'completed', "created_by" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1b670b7f687d8b8c58ef8d4629a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "inventory_batches_tenant_branch_index" ON "inventory_batches" ("tenant_id", "branch_id") `);
        await queryRunner.query(`CREATE TABLE "order_item_taxes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_item_id" uuid NOT NULL, "tax_config_id" uuid NOT NULL, "tax_name_snapshot" character varying(100) NOT NULL, "tax_rate_snapshot" numeric(5,2) NOT NULL, "is_inclusive" boolean NOT NULL, "tax_amount" numeric(12,2) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3eb1f304c128a159923664b703a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "product_id" uuid NOT NULL, "quantity" numeric(12,3) NOT NULL, "unit_price" numeric(12,2) NOT NULL, "line_subtotal" numeric(12,2) NOT NULL DEFAULT '0', "line_discount_amount" numeric(12,2) NOT NULL DEFAULT '0', "order_discount_share" numeric(12,2) NOT NULL DEFAULT '0', "discounted_amount" numeric(12,2) NOT NULL DEFAULT '0', "base_amount" numeric(12,2) NOT NULL DEFAULT '0', "tax_amount" numeric(12,2) NOT NULL DEFAULT '0', "line_total" numeric(12,2) NOT NULL DEFAULT '0', "product_name_snapshot" character varying(255), "sku_snapshot" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_discounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "discount_preset_id" uuid NOT NULL, "computed_amount" numeric(12,2) NOT NULL DEFAULT '0', "preset_name_snapshot" character varying(100) NOT NULL, "type_snapshot" character varying(16) NOT NULL, "value_snapshot" numeric(12,2) NOT NULL, "scope_snapshot" character varying(16) NOT NULL, "order_item_id_snapshot" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c4a40a77b36d106ef37580a6341" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "created_by" uuid NOT NULL, "customer_id" uuid, "order_number" character varying(64), "status" character varying(32) NOT NULL DEFAULT 'draft', "subtotal_amount" numeric(12,2) NOT NULL DEFAULT '0', "discount_amount" numeric(12,2) NOT NULL DEFAULT '0', "tax_amount" numeric(12,2) NOT NULL DEFAULT '0', "total_amount" numeric(12,2) NOT NULL DEFAULT '0', "paid_amount" numeric(12,2) NOT NULL DEFAULT '0', "notes" text, "client_event_id" uuid, "cancelled_at" TIMESTAMP, "cancelled_by" uuid, "cancellation_reason" text, "completed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_orders_branch_creator_date" ON "orders" ("branch_id", "created_by", "created_at") `);
        await queryRunner.query(`CREATE INDEX "orders_tenant_branch_status_created_index" ON "orders" ("tenant_id", "branch_id", "status", "created_at") `);
        await queryRunner.query(`CREATE TABLE "inventory_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "product_id" uuid NOT NULL, "movement_type" character varying(32) NOT NULL, "quantity" numeric(12,3) NOT NULL, "unit_cost" numeric(12,2), "order_id" uuid, "batch_id" uuid, "client_event_id" uuid, "note" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d7597827c1dcffae889db3ab873" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "inventory_movements_tenant_branch_product_created_index" ON "inventory_movements" ("tenant_id", "branch_id", "product_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "inventory_balances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "product_id" uuid NOT NULL, "on_hand_qty" numeric(12,3) NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "inventory_balances_tenant_branch_product_unique" UNIQUE ("tenant_id", "branch_id", "product_id"), CONSTRAINT "PK_4abb5082c6c3dcf55f1b124d2ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "branch_product_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "product_id" uuid NOT NULL, "low_stock_threshold" numeric(12,3), "is_available" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "branch_product_configs_tenant_branch_product_unique" UNIQUE ("tenant_id", "branch_id", "product_id"), CONSTRAINT "PK_7033979f79062e787d04e6b67b5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_number_sequences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "branch_id" uuid NOT NULL, "sequence_date" character varying(10) NOT NULL, "last_sequence" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4fddcb23b0a9fad8917b690cb42" UNIQUE ("branch_id", "sequence_date"), CONSTRAINT "PK_5906682f86316bfbadf8259001c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "method" character varying(32) NOT NULL DEFAULT 'cash', "amount" numeric(12,2) NOT NULL, "cash_tendered" numeric(12,2), "status" character varying(32) NOT NULL DEFAULT 'completed', "client_event_id" uuid, "received_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "branch_id" uuid, "actor_id" uuid, "event_type" character varying(100) NOT NULL, "entity_type" character varying(100) NOT NULL, "entity_id" uuid NOT NULL, "payload" jsonb NOT NULL, "occurred_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "audit_logs_entity_index" ON "audit_logs" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "audit_logs_tenant_event_time_index" ON "audit_logs" ("tenant_id", "event_type", "occurred_at") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "resource" character varying(50) NOT NULL, "action" character varying(50) NOT NULL, "description" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8dad765629e83229da6feda1c1d" UNIQUE ("code"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE TABLE "platform_admins" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "password_hash" character varying(255) NOT NULL, "full_name" character varying(255) NOT NULL, "status" character varying(32) NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7ddfa7abfaf477f671ccc566c83" UNIQUE ("email"), CONSTRAINT "PK_faecb3398d1962507b44c76e4f0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "receipt_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "token" character varying(16) NOT NULL, "expires_at" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_832ab565236b7af01a261018300" UNIQUE ("order_id"), CONSTRAINT "UQ_6714e1c6f7462f2721868138deb" UNIQUE ("token"), CONSTRAINT "PK_3e25c0af3cbcee449a1733bde39" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8fb425331493e724b9edfb0d7c" ON "receipt_tokens" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "user_branches" ("user_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_79e020eef929e23dfdd6f9b8720" PRIMARY KEY ("user_id", "branch_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7252d91dd610730c97d6b58ae7" ON "user_branches" ("branch_id") `);
        await queryRunner.query(`CREATE TABLE "branch_groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "parent_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "branch_groups_tenant_name_unique" UNIQUE ("tenant_id", "name"), CONSTRAINT "PK_21d87e3f788125c204917ac83bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_40a89724d6fc8676d7455ae445" ON "branch_groups" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3296a32f7689cac6a53fa3acfd" ON "branch_groups" ("parent_id") `);
        await queryRunner.query(`CREATE TABLE "branch_group_members" ("branch_group_id" uuid NOT NULL, "branch_id" uuid NOT NULL, CONSTRAINT "PK_f376c4ba20d3ce29c943ea6e032" PRIMARY KEY ("branch_group_id", "branch_id"))`);
        await queryRunner.query(`CREATE TABLE "branch_product_prices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "product_id" uuid NOT NULL, "price" numeric(12,2) NOT NULL, "cost" numeric(12,2), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "branch_product_prices_branch_product_unique" UNIQUE ("branch_id", "product_id"), CONSTRAINT "PK_40e208f04915a740a2beeb272ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9c3c20f130d35f820b52c21e82" ON "branch_product_prices" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "stock_transfers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "transfer_number" character varying(50) NOT NULL, "from_branch_id" uuid NOT NULL, "to_branch_id" uuid NOT NULL, "status" character varying(32) NOT NULL DEFAULT 'draft', "initiated_by" uuid NOT NULL, "received_by" uuid, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "completed_at" TIMESTAMP, CONSTRAINT "UQ_e6943db71fc295dca9bbe16b85c" UNIQUE ("transfer_number"), CONSTRAINT "PK_ef738a3a4a578c7f1802c1bb50a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock_transfer_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "transfer_id" uuid NOT NULL, "product_id" uuid NOT NULL, "quantity" numeric(12,2) NOT NULL, "received_quantity" numeric(12,2), CONSTRAINT "PK_8acee6121ab8a5135dc84495588" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_fda619979f40a6a44fc9baf02c3" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_5d4fe23b360b1b9e16a3f41727f" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_88cea2dc9c31951d06437879b40" FOREIGN KEY ("parent_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_groups" ADD CONSTRAINT "FK_306659a1d6a86123d609f999847" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9c365ebf78f0e8a6d9e4827ea70" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_fa5577d2a5137745afb4f4266bd" FOREIGN KEY ("tax_group_id") REFERENCES "tax_groups"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_e59a01f4fe46ebbece575d9a0fc" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_109638590074998bb72a2f2cf08" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_4dcacd1b99b93f7ad61ee69c3a3" FOREIGN KEY ("default_branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_configs" ADD CONSTRAINT "FK_1b412e9be287124eafa9eef4ba1" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_configs" ADD CONSTRAINT "FK_ecf3bdebe751a987adbc808f3af" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_configs" ADD CONSTRAINT "FK_dafaef97638d550f09b860504b7" FOREIGN KEY ("tax_group_id") REFERENCES "tax_groups"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_presets" ADD CONSTRAINT "FK_74685440e8b0b8f1b330594bf2e" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_preset_branches" ADD CONSTRAINT "FK_216df044bfba929116561fe7662" FOREIGN KEY ("discount_preset_id") REFERENCES "discount_presets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_preset_branches" ADD CONSTRAINT "FK_bdb5f2d628282b6080e6d7c7e25" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_batches" ADD CONSTRAINT "FK_fe7ad0d447c244d7063e66f5961" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_batches" ADD CONSTRAINT "FK_81965eaff8df70eead18614595d" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_batches" ADD CONSTRAINT "FK_100323267836a7f6dca2d11845a" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item_taxes" ADD CONSTRAINT "FK_fee1162007eb193add008cf883b" FOREIGN KEY ("order_item_id") REFERENCES "order_items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item_taxes" ADD CONSTRAINT "FK_fba22a11afdd27ebb2d78107135" FOREIGN KEY ("tax_config_id") REFERENCES "tax_configs"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_9263386c35b6b242540f9493b00" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_discounts" ADD CONSTRAINT "FK_e7b488cebe333f449398769b2cc" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_discounts" ADD CONSTRAINT "FK_bf56ec30823711c98184b593295" FOREIGN KEY ("discount_preset_id") REFERENCES "discount_presets"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_527dd6efd5f3402f729c6b3e826" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_17b723da2c12837f4bc21e33398" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_574a2f0932043d4e4baf188ee05" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_08344cc99d67ce2b3bd27831e13" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_1ab8073a9fb9462a50ac175cb21" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_5c3bec1682252c36fa161587738" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_94f4f29857aa6b3586e1528be04" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_0d8d237c78afa95bb19afcb5172" FOREIGN KEY ("batch_id") REFERENCES "inventory_batches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_balances" ADD CONSTRAINT "FK_af8b36f15ba614dbe4432c12200" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_balances" ADD CONSTRAINT "FK_cd1b2668b4259a82c19c80d3232" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_balances" ADD CONSTRAINT "FK_328cfceff155d8d993ca74ab3e5" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_product_configs" ADD CONSTRAINT "FK_3c808828e6011b6e254ecdbed5a" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_product_configs" ADD CONSTRAINT "FK_1c8d12e74d7e3f12a7179e033ba" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_product_configs" ADD CONSTRAINT "FK_83ef2001ce78e0c171868cfbcf0" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_number_sequences" ADD CONSTRAINT "FK_b7d07f2733ce31f8427cd9bc16f" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_b2f7b823a21562eeca20e72b006" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_9109b53fca5cef7720aca72974d" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_b50ef2c264e6c0fda8c639935af" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receipt_tokens" ADD CONSTRAINT "FK_832ab565236b7af01a261018300" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receipt_tokens" ADD CONSTRAINT "FK_8fb425331493e724b9edfb0d7cf" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_branches" ADD CONSTRAINT "FK_a93a8dec13e6204974dd67386ed" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_branches" ADD CONSTRAINT "FK_7252d91dd610730c97d6b58ae79" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_groups" ADD CONSTRAINT "FK_40a89724d6fc8676d7455ae445e" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_groups" ADD CONSTRAINT "FK_3296a32f7689cac6a53fa3acfd9" FOREIGN KEY ("parent_id") REFERENCES "branch_groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_group_members" ADD CONSTRAINT "FK_dbf7c1f99cce63d9652224265e9" FOREIGN KEY ("branch_group_id") REFERENCES "branch_groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_group_members" ADD CONSTRAINT "FK_585c6727dd8ce9a46cd5cf2cece" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_product_prices" ADD CONSTRAINT "FK_9c3c20f130d35f820b52c21e827" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_product_prices" ADD CONSTRAINT "FK_7716910a14a7f96152f49380fa0" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_product_prices" ADD CONSTRAINT "FK_cb3c85dadd58ecb3e3b1c45df96" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_65e78a521cbef64720491f3a0da" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_9b573720e43ecb7bb135ce7bfa5" FOREIGN KEY ("from_branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_4a22daeaaf163fb7508aceff814" FOREIGN KEY ("to_branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_8722a67728dfad3352731800b83" FOREIGN KEY ("initiated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfer_items" ADD CONSTRAINT "FK_6a0f024e84c92b964c516aa7b79" FOREIGN KEY ("transfer_id") REFERENCES "stock_transfers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfer_items" ADD CONSTRAINT "FK_cb5cee89889c9acfd70cd519810" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "stock_transfer_items" DROP CONSTRAINT "FK_cb5cee89889c9acfd70cd519810"`);
        await queryRunner.query(`ALTER TABLE "stock_transfer_items" DROP CONSTRAINT "FK_6a0f024e84c92b964c516aa7b79"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_8722a67728dfad3352731800b83"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_4a22daeaaf163fb7508aceff814"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_9b573720e43ecb7bb135ce7bfa5"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_65e78a521cbef64720491f3a0da"`);
        await queryRunner.query(`ALTER TABLE "branch_product_prices" DROP CONSTRAINT "FK_cb3c85dadd58ecb3e3b1c45df96"`);
        await queryRunner.query(`ALTER TABLE "branch_product_prices" DROP CONSTRAINT "FK_7716910a14a7f96152f49380fa0"`);
        await queryRunner.query(`ALTER TABLE "branch_product_prices" DROP CONSTRAINT "FK_9c3c20f130d35f820b52c21e827"`);
        await queryRunner.query(`ALTER TABLE "branch_group_members" DROP CONSTRAINT "FK_585c6727dd8ce9a46cd5cf2cece"`);
        await queryRunner.query(`ALTER TABLE "branch_group_members" DROP CONSTRAINT "FK_dbf7c1f99cce63d9652224265e9"`);
        await queryRunner.query(`ALTER TABLE "branch_groups" DROP CONSTRAINT "FK_3296a32f7689cac6a53fa3acfd9"`);
        await queryRunner.query(`ALTER TABLE "branch_groups" DROP CONSTRAINT "FK_40a89724d6fc8676d7455ae445e"`);
        await queryRunner.query(`ALTER TABLE "user_branches" DROP CONSTRAINT "FK_7252d91dd610730c97d6b58ae79"`);
        await queryRunner.query(`ALTER TABLE "user_branches" DROP CONSTRAINT "FK_a93a8dec13e6204974dd67386ed"`);
        await queryRunner.query(`ALTER TABLE "receipt_tokens" DROP CONSTRAINT "FK_8fb425331493e724b9edfb0d7cf"`);
        await queryRunner.query(`ALTER TABLE "receipt_tokens" DROP CONSTRAINT "FK_832ab565236b7af01a261018300"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_b50ef2c264e6c0fda8c639935af"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_9109b53fca5cef7720aca72974d"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_b2f7b823a21562eeca20e72b006"`);
        await queryRunner.query(`ALTER TABLE "order_number_sequences" DROP CONSTRAINT "FK_b7d07f2733ce31f8427cd9bc16f"`);
        await queryRunner.query(`ALTER TABLE "branch_product_configs" DROP CONSTRAINT "FK_83ef2001ce78e0c171868cfbcf0"`);
        await queryRunner.query(`ALTER TABLE "branch_product_configs" DROP CONSTRAINT "FK_1c8d12e74d7e3f12a7179e033ba"`);
        await queryRunner.query(`ALTER TABLE "branch_product_configs" DROP CONSTRAINT "FK_3c808828e6011b6e254ecdbed5a"`);
        await queryRunner.query(`ALTER TABLE "inventory_balances" DROP CONSTRAINT "FK_328cfceff155d8d993ca74ab3e5"`);
        await queryRunner.query(`ALTER TABLE "inventory_balances" DROP CONSTRAINT "FK_cd1b2668b4259a82c19c80d3232"`);
        await queryRunner.query(`ALTER TABLE "inventory_balances" DROP CONSTRAINT "FK_af8b36f15ba614dbe4432c12200"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_0d8d237c78afa95bb19afcb5172"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_94f4f29857aa6b3586e1528be04"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_5c3bec1682252c36fa161587738"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_1ab8073a9fb9462a50ac175cb21"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_08344cc99d67ce2b3bd27831e13"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_574a2f0932043d4e4baf188ee05"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_17b723da2c12837f4bc21e33398"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_527dd6efd5f3402f729c6b3e826"`);
        await queryRunner.query(`ALTER TABLE "order_discounts" DROP CONSTRAINT "FK_bf56ec30823711c98184b593295"`);
        await queryRunner.query(`ALTER TABLE "order_discounts" DROP CONSTRAINT "FK_e7b488cebe333f449398769b2cc"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_9263386c35b6b242540f9493b00"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "order_item_taxes" DROP CONSTRAINT "FK_fba22a11afdd27ebb2d78107135"`);
        await queryRunner.query(`ALTER TABLE "order_item_taxes" DROP CONSTRAINT "FK_fee1162007eb193add008cf883b"`);
        await queryRunner.query(`ALTER TABLE "inventory_batches" DROP CONSTRAINT "FK_100323267836a7f6dca2d11845a"`);
        await queryRunner.query(`ALTER TABLE "inventory_batches" DROP CONSTRAINT "FK_81965eaff8df70eead18614595d"`);
        await queryRunner.query(`ALTER TABLE "inventory_batches" DROP CONSTRAINT "FK_fe7ad0d447c244d7063e66f5961"`);
        await queryRunner.query(`ALTER TABLE "discount_preset_branches" DROP CONSTRAINT "FK_bdb5f2d628282b6080e6d7c7e25"`);
        await queryRunner.query(`ALTER TABLE "discount_preset_branches" DROP CONSTRAINT "FK_216df044bfba929116561fe7662"`);
        await queryRunner.query(`ALTER TABLE "discount_presets" DROP CONSTRAINT "FK_74685440e8b0b8f1b330594bf2e"`);
        await queryRunner.query(`ALTER TABLE "tax_configs" DROP CONSTRAINT "FK_dafaef97638d550f09b860504b7"`);
        await queryRunner.query(`ALTER TABLE "tax_configs" DROP CONSTRAINT "FK_ecf3bdebe751a987adbc808f3af"`);
        await queryRunner.query(`ALTER TABLE "tax_configs" DROP CONSTRAINT "FK_1b412e9be287124eafa9eef4ba1"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_4dcacd1b99b93f7ad61ee69c3a3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_109638590074998bb72a2f2cf08"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_e59a01f4fe46ebbece575d9a0fc"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_fa5577d2a5137745afb4f4266bd"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9c365ebf78f0e8a6d9e4827ea70"`);
        await queryRunner.query(`ALTER TABLE "tax_groups" DROP CONSTRAINT "FK_306659a1d6a86123d609f999847"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_88cea2dc9c31951d06437879b40"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_5d4fe23b360b1b9e16a3f41727f"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_fda619979f40a6a44fc9baf02c3"`);
        await queryRunner.query(`DROP TABLE "stock_transfer_items"`);
        await queryRunner.query(`DROP TABLE "stock_transfers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c3c20f130d35f820b52c21e82"`);
        await queryRunner.query(`DROP TABLE "branch_product_prices"`);
        await queryRunner.query(`DROP TABLE "branch_group_members"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3296a32f7689cac6a53fa3acfd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40a89724d6fc8676d7455ae445"`);
        await queryRunner.query(`DROP TABLE "branch_groups"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7252d91dd610730c97d6b58ae7"`);
        await queryRunner.query(`DROP TABLE "user_branches"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8fb425331493e724b9edfb0d7c"`);
        await queryRunner.query(`DROP TABLE "receipt_tokens"`);
        await queryRunner.query(`DROP TABLE "platform_admins"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."audit_logs_tenant_event_time_index"`);
        await queryRunner.query(`DROP INDEX "public"."audit_logs_entity_index"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TABLE "order_number_sequences"`);
        await queryRunner.query(`DROP TABLE "branch_product_configs"`);
        await queryRunner.query(`DROP TABLE "inventory_balances"`);
        await queryRunner.query(`DROP INDEX "public"."inventory_movements_tenant_branch_product_created_index"`);
        await queryRunner.query(`DROP TABLE "inventory_movements"`);
        await queryRunner.query(`DROP INDEX "public"."orders_tenant_branch_status_created_index"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_branch_creator_date"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TABLE "order_discounts"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP TABLE "order_item_taxes"`);
        await queryRunner.query(`DROP INDEX "public"."inventory_batches_tenant_branch_index"`);
        await queryRunner.query(`DROP TABLE "inventory_batches"`);
        await queryRunner.query(`DROP TABLE "discount_preset_branches"`);
        await queryRunner.query(`DROP INDEX "public"."discount_presets_tenant_id_index"`);
        await queryRunner.query(`DROP TABLE "discount_presets"`);
        await queryRunner.query(`DROP INDEX "public"."tax_configs_tenant_branch_index"`);
        await queryRunner.query(`DROP INDEX "public"."tax_configs_tenant_branch_group_index"`);
        await queryRunner.query(`DROP TABLE "tax_configs"`);
        await queryRunner.query(`DROP INDEX "public"."users_tenant_id_index"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP INDEX "public"."products_tenant_id_index"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP INDEX "public"."tax_groups_tenant_id_index"`);
        await queryRunner.query(`DROP TABLE "tax_groups"`);
        await queryRunner.query(`DROP INDEX "public"."categories_tenant_id_index"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP INDEX "public"."branches_tenant_id_index"`);
        await queryRunner.query(`DROP TABLE "branches"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
    }

}
